package Algorithms.FunctionOpt;


import java.awt.Color;
import java.awt.Window;
import javax.swing.JComponent;
import javax.swing.SwingUtilities;
import net.objecthunter.exp4j.ExpressionBuilder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author i62gorej
 */
public class genFunction extends javax.swing.JPanel {

    /**
     * Creates new form genFunction
     */
    public genFunction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtFunction = new javax.swing.JTextField();
        sliderRange = new javax.swing.JSlider();
        txtRange = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnSin = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnSinh = new javax.swing.JButton();
        btnCosh = new javax.swing.JButton();
        btnTanh = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnLogB = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnVarZ = new javax.swing.JButton();
        btnPi = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnVarY = new javax.swing.JButton();
        btnLn = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        sliderPrecision = new javax.swing.JSlider();
        txtPrecision = new javax.swing.JTextField();
        btnVarX = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnRightP = new javax.swing.JButton();
        btnMult = new javax.swing.JButton();
        btnMinus1 = new javax.swing.JButton();
        btnLeftP = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 600));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(600, 300));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        txtFunction.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFunction.setToolTipText("sin(2*x)+cos(3-y)*(z+3*x+2*y)");
        txtFunction.setDoubleBuffered(true);

        sliderRange.setMaximum(200);
        sliderRange.setMinorTickSpacing(5);
        sliderRange.setPaintLabels(true);
        sliderRange.setToolTipText("Value");
        sliderRange.setValue(0);
        sliderRange.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderRangeStateChanged(evt);
            }
        });

        txtRange.setEditable(false);
        txtRange.setText("0");

        jButton1.setText("Ejecutar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setText("Rango Numérico");
        jTextField1.setBorder(null);

        btnSin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSin.setText("Sin");
        btnSin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSinMousePressed(evt);
            }
        });

        btnCos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCos.setText("Cos");
        btnCos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCosMousePressed(evt);
            }
        });

        btnTan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTan.setText("Tan");
        btnTan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTanMousePressed(evt);
            }
        });

        btnSinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSinh.setText("Sinh");
        btnSinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSinhMousePressed(evt);
            }
        });

        btnCosh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCosh.setText("Cosh");
        btnCosh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCoshMousePressed(evt);
            }
        });

        btnTanh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTanh.setText("Tanh");
        btnTanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTanhMousePressed(evt);
            }
        });

        btnLog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLog.setText("log");
        btnLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogMousePressed(evt);
            }
        });

        btnLogB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogB.setText("logb2");
        btnLogB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogBMousePressed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setText("CLR");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnClearMousePressed(evt);
            }
        });

        btnVarZ.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVarZ.setText("Z");
        btnVarZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVarZMousePressed(evt);
            }
        });

        btnPi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPi.setText("PI");
        btnPi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPiMousePressed(evt);
            }
        });

        btnDiv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDiv.setText("/");
        btnDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDivMousePressed(evt);
            }
        });

        btnVarY.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVarY.setText("Y");
        btnVarY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVarYMousePressed(evt);
            }
        });

        btnLn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLn.setText("ln");
        btnLn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLnMousePressed(evt);
            }
        });

        btnE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnE.setText("e");
        btnE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEMousePressed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setText("Precisión");
        jTextField2.setBorder(null);

        sliderPrecision.setMaximum(10);
        sliderPrecision.setMinorTickSpacing(5);
        sliderPrecision.setPaintLabels(true);
        sliderPrecision.setToolTipText("Value");
        sliderPrecision.setValue(0);
        sliderPrecision.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderPrecisionStateChanged(evt);
            }
        });

        txtPrecision.setEditable(false);
        txtPrecision.setText("0");

        btnVarX.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVarX.setText("X");
        btnVarX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVarXMousePressed(evt);
            }
        });

        btnPlus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPlus.setText("+");
        btnPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPlusMousePressed(evt);
            }
        });

        btnRightP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRightP.setText(")");
        btnRightP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRightPMousePressed(evt);
            }
        });

        btnMult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMult.setText("*");
        btnMult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMultMousePressed(evt);
            }
        });

        btnMinus1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMinus1.setText("-");
        btnMinus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMinus1MousePressed(evt);
            }
        });

        btnLeftP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLeftP.setText("(");
        btnLeftP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLeftPMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(sliderRange, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtRange, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(sliderPrecision, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtPrecision, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnVarX)
                        .addGap(11, 11, 11)
                        .addComponent(btnVarY)
                        .addGap(11, 11, 11)
                        .addComponent(btnVarZ))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnLn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnLogB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnPlus)
                        .addGap(9, 9, 9)
                        .addComponent(btnMinus1)
                        .addGap(13, 13, 13)
                        .addComponent(btnLeftP))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnMult)
                        .addGap(11, 11, 11)
                        .addComponent(btnDiv)
                        .addGap(13, 13, 13)
                        .addComponent(btnRightP))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliderPrecision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSin)
                    .addComponent(btnCos)
                    .addComponent(btnTan)
                    .addComponent(btnVarX)
                    .addComponent(btnVarY)
                    .addComponent(btnVarZ))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSinh)
                    .addComponent(btnCosh)
                    .addComponent(btnTanh))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLog)
                    .addComponent(btnLn)
                    .addComponent(btnLogB)
                    .addComponent(btnPlus)
                    .addComponent(btnMinus1)
                    .addComponent(btnLeftP))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPi)
                    .addComponent(btnE)
                    .addComponent(btnClear)
                    .addComponent(btnMult)
                    .addComponent(btnDiv)
                    .addComponent(btnRightP))
                .addGap(17, 17, 17)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 256, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sliderRangeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderRangeStateChanged
        // TODO add your handling code here:
        txtRange.setText(""+this.sliderRange.getValue());
        
    }//GEN-LAST:event_sliderRangeStateChanged

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        JComponent comp = (JComponent) evt.getSource();
        Window win = SwingUtilities.getWindowAncestor(comp);
        win.dispose();
    }//GEN-LAST:event_jButton1MousePressed

    private void sliderPrecisionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderPrecisionStateChanged
        // TODO add your handling code here:
        txtPrecision.setText(""+sliderPrecision.getValue());
    }//GEN-LAST:event_sliderPrecisionStateChanged

    private void btnClearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMousePressed
        // TODO add your handling code here:
        txtFunction.setText("");
    }//GEN-LAST:event_btnClearMousePressed

    private void btnSinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSinMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"sin(");
    }//GEN-LAST:event_btnSinMousePressed

    private void btnCosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCosMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"cos(");
    }//GEN-LAST:event_btnCosMousePressed

    private void btnTanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTanMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"tan(");
    }//GEN-LAST:event_btnTanMousePressed

    private void btnSinhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSinhMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"sinh(");
    }//GEN-LAST:event_btnSinhMousePressed

    private void btnCoshMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCoshMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"cosh(");
    }//GEN-LAST:event_btnCoshMousePressed

    private void btnTanhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTanhMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"tanh(");
    }//GEN-LAST:event_btnTanhMousePressed

    private void btnLogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"log10(");
    }//GEN-LAST:event_btnLogMousePressed

    private void btnLnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLnMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"log(");
    }//GEN-LAST:event_btnLnMousePressed

    private void btnLogBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogBMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"log2(");
    }//GEN-LAST:event_btnLogBMousePressed

    private void btnPiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPiMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"pi");
    }//GEN-LAST:event_btnPiMousePressed

    private void btnEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"e");
    }//GEN-LAST:event_btnEMousePressed

    private void btnPlusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"+");
    }//GEN-LAST:event_btnPlusMousePressed

    private void btnRightPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRightPMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+")");
    }//GEN-LAST:event_btnRightPMousePressed

    private void btnMultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"*");
    }//GEN-LAST:event_btnMultMousePressed

    private void btnDivMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"/");
    }//GEN-LAST:event_btnDivMousePressed

    private void btnMinus1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinus1MousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"-");
    }//GEN-LAST:event_btnMinus1MousePressed

    private void btnLeftPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLeftPMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"(");
    }//GEN-LAST:event_btnLeftPMousePressed

    private void btnVarXMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVarXMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"x");
    }//GEN-LAST:event_btnVarXMousePressed

    private void btnVarYMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVarYMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"y");
    }//GEN-LAST:event_btnVarYMousePressed

    private void btnVarZMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVarZMousePressed
        // TODO add your handling code here:
        txtFunction.setText(txtFunction.getText()+"z");
    }//GEN-LAST:event_btnVarZMousePressed
    public String getFunct(){
        return this.txtFunction.getText();
    }
    
    public Integer getRange(){
        return this.sliderRange.getValue();
    }
    public Integer getPrecision(){
        return this.sliderPrecision.getValue();
    }    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnCosh;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnLeftP;
    private javax.swing.JButton btnLn;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnLogB;
    private javax.swing.JButton btnMinus1;
    private javax.swing.JButton btnMult;
    private javax.swing.JButton btnPi;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnRightP;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnSinh;
    private javax.swing.JButton btnTan;
    private javax.swing.JButton btnTanh;
    private javax.swing.JButton btnVarX;
    private javax.swing.JButton btnVarY;
    private javax.swing.JButton btnVarZ;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JSlider sliderPrecision;
    private javax.swing.JSlider sliderRange;
    private javax.swing.JTextField txtFunction;
    private javax.swing.JTextField txtPrecision;
    private javax.swing.JTextField txtRange;
    // End of variables declaration//GEN-END:variables
}
